Revolt support
meower-media-co/Meower-Svelte pull request #102
Opened 2023-03-11 22:04 UTC by showierdata9978

2023-03-11 22:11 UTC, JoshAtticus commented
When you hover over the bridged tag, it says the message is from a discord server. You should change it to say something like “This message is from an external platform”

2023-03-11 22:28 UTC, JoshAtticus commented
Pfps and profiles are broken

![image](https://user-images.githubusercontent.com/72828296/224514237-58dd7aa1-1342-4a38-9e71-27868fb63775.png)

2023-03-11 22:52 UTC, JoshAtticus commented
@showierdata9978

2023-03-11 23:52 UTC, williamhorning requested changes
Fix this gramatical error and have Revower profile links actually work before merging

2023-03-11 23:52 UTC, williamhorning commented on src/lib/Post.svelte
> +						title="This post is bridged from a external service by a bot"
```suggestion
						title="This post is bridged from an external service by a bot"
```

2023-03-13 23:16 UTC, JoshAtticus commented
> Fix this grammatical error and have Revower profile links actually work before merging

Fixed @williamhorning

2023-03-13 23:17 UTC, williamhorning approved these changes
@JoshAtticus LGTM then

2023-03-13 23:56 UTC, merged