Use Mutant Remix for emojis
meower-media-co/Meower-Svelte pull request #141
Opened 2023-05-01 13:20 UTC by mdwalters

Not really sure if I should make a PR for this, but I can switch it to Twemoji if requested.

2023-05-01 13:26 UTC, showierdata9978 requested changes
never use @html, and install via npm

2023-05-01 13:26 UTC, showierdata9978 commented
sorry for the ping

2023-05-01 13:52 UTC, CST1229 commented
i think we should use twemoji

2023-05-03 04:30 UTC, mdwalters commented
@CST1229 @showierdata9978 i fixed, and it works with all emojis now

2023-05-03 04:33 UTC, showierdata9978 commented
YOU STILL USE `@html` NEVER USE IT FOR USER GENERATED CONTENT

2023-05-03 04:38 UTC, CST1229 commented
you should probably escape the HTML (converting < into `@lt;` etc) instead of just sanitizing it

2023-05-03 11:42 UTC, mdwalters commented
> YOU STILL USE `@html` NEVER USE IT FOR USER GENERATED CONTENT

and how am i going to get twemoji to work without `@html`?

2023-05-03 11:57 UTC, MikeDev101 commented
> One who does not learn from the past is doomed to repeat it.
https://www.youtube.com/watch?v=ykoACojHgeo

2023-05-03 12:20 UTC, CST1229 commented
> and how am i going to get twemoji to work without `@html`?

https://svelte.dev/docs#template-syntax-svelte-element

(probably parsing emojis manually instead of using a library)

2023-05-03 15:36 UTC, mdwalters commented
> > One who does not learn from the past is doomed to repeat it.
> > https://www.youtube.com/watch?v=ykoACojHgeo

ok

2023-05-03 15:41 UTC, showierdata9978 submitted a review, later dismissed
im not accepting until no `@html`

2023-05-03 16:40 UTC, mdwalters commented
~~strict~~

2023-05-08 03:42 UTC, Bloctans commented
i already did this just for it to be removed due to maxCDN being a tracking company

2023-05-08 18:10 UTC, mdwalters commented
maxcdn shut down ._.

2023-05-08 18:54 UTC, showierdata9978 commented
actually the only way im going to allow Emojis is if we parse it ourselves. 

Twemoji uses innerHTML

2023-05-14 03:19 UTC, Bloctans commented
should this be closed?

2023-05-14 03:20 UTC, showierdata9978 commented
needs to be fully redone

On Sat, May 13, 2023, 10:19 PM Bloctans ***@***.***> wrote:

> should this be closed?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/meower-media-co/Meower-Svelte/pull/141#issuecomment-1546796824>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQHW4PZDHDRQ7E4AN4AJSD3XGBFK7ANCNFSM6AAAAAAXRYQJOY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-14 15:12 UTC, mdwalters commented
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

On Sat, May 13, 2023 at 11:20 PM ShowierData9978 ***@***.***>
wrote:

> needs to be fully redone
>
> On Sat, May 13, 2023, 10:19 PM Bloctans ***@***.***> wrote:
>
> > should this be closed?
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/meower-media-co/Meower-Svelte/pull/141#issuecomment-1546796824
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AQHW4PZDHDRQ7E4AN4AJSD3XGBFK7ANCNFSM6AAAAAAXRYQJOY
> >
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/meower-media-co/Meower-Svelte/pull/141#issuecomment-1546796954>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQCU4NQDSL33EKYIXXI6PBDXGBFPJANCNFSM6AAAAAAXRYQJOY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-14 23:11 UTC, showierdata9978 commented
still uses `@html`

2023-05-14 23:41 UTC, CST1229 commented on src/lib/twemoji-utils.js
> +}
probably a better way to do this:
```suggestion
export function toHTMLElement(text) {
    const filteredText = text
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&apos;");
    
    const span = document.createElement("span");
    const p = document.createElement("p");
    p.innerText = filteredText;
    span.appendChild(p);
    return span;
}
```
and add `white-space: pre-wrap;` as a style to `.post-content` (so newlines and duplicated spaces are preserved)

2023-05-14 23:41 UTC, CST1229 commented
> still uses `@html`

that doesn't mean it's bad or vulnerable to XSS; you just have to be careful with it

2023-05-15 00:18 UTC, mdwalters commented
> still uses `@html`

but it uses cst's escape trick

2023-05-16 15:30 UTC, mdwalters commented
@showierdata9978 pls?

2023-05-16 15:53 UTC, CST1229 approved these changes

2023-06-05 23:05 UTC, tnix100 commented
@showierdata9978 please re-review.

2023-06-05 23:07 UTC, showierdata9978 commented
![image](https://github.com/meower-media-co/Meower-Svelte/assets/68120127/f8ff85df-ac8d-411d-8004-8790105eac5a)

2023-06-06 04:09 UTC, CST1229 commented
> ![image](https://user-images.githubusercontent.com/68120127/243504472-f8ff85df-ac8d-411d-8004-8790105eac5a.png)

it's probably fine imo

2023-06-06 07:03 UTC, tnix100 commented
As long as it's not vulnerable to XSS, then it's fine.

2023-06-06 07:19 UTC, tnix100 approved these changes

2023-06-06 12:39 UTC, CST1229 approved these changes

2023-06-06 15:20 UTC, mdwalters commented
> > 
> 
> Now we just gotta wait for showier to change their review.

*infinity years later...*

2023-06-07 04:35 UTC, merged